name: CI
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  node:
    runs-on: ubuntu-latest
    env:
      PORT: "3000"
      DATABASE_URL: "file:./prisma/dev.db"
      ADMIN_USER: "admin"
      ADMIN_PASS: "admin123"
      BASE_URL: "http://localhost:3000"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm install
      - run: npx prisma generate
      - run: npx prisma migrate deploy
      - run: nohup node app.js &
      - run: |
          sleep 2
          curl -fsS http://localhost:3000/salud
          curl -fsS -H "Content-Type: application/json" -d '{"urlOriginal":"https://example.com"}' http://localhost:3000/api/links
      - run: pkill -f "node app.js" || true
